export const NOTE_SET_ALL = 'NOTE_SET_ALL'
export const NOTE_SET = 'NOTE_SET'
export const NOTE_APPEND = 'NOTE_APPEND'
export const NOTE_CHANGE = 'NOTE_CHANGE'
export const NOTE_REMOVE = 'NOTE_REMOVE'

export const NOTE_FETCH_ALL = 'NOTE_FETCH_ALL'
export const NOTE_FETCH_FOLDER = 'NOTE_FETCH_FOLDER'
export const NOTE_FETCH_TAG = 'NOTE_FETCH_TAG'
export const NOTE_CREATE = 'NOTE_CREATE'
export const NOTE_DELETE = 'NOTE_DELETE'

export default {
  NOTE_SET_ALL,
  NOTE_SET,
  NOTE_APPEND,
  NOTE_CHANGE,
  NOTE_REMOVE,
  NOTE_FETCH_ALL,
  NOTE_CREATE,
  NOTE_DELETE,
  NOTE_FETCH_FOLDER,
  NOTE_FETCH_TAG
}
